version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - '5173:5173'

  json-server:
    build:
      context: .
      dockerfile: Dockerfile.jsonserver
    volumes:
      - ./mock:/server/mock
    ports:
      - '5000:5000'
