# Dockerfile.cypress

# Use Cypress image
FROM cypress/included:9.2.0

# Set working directory
WORKDIR /e2e

# Copy package.json and yarn.lock
COPY package*.json yarn.lock ./

# Install dependencies
RUN yarn install

# Copy the rest of your app's source code
COPY . .
